### ISSUE TITLE
se.warting.signatureview.views.SignaturePad.addBezier - NullPointerException

### ISSUE THREAD

**Issue by ashik169** [warting/android-signaturepad#208]
The app is getting crashes on v0.0.21

Fatal Exception: java.lang.NullPointerException:
       at se.warting.signatureview.views.SignaturePad.addBezier(SignaturePad.kt:485)
       at se.warting.signatureview.views.SignaturePad.addTimedPoint(SignaturePad.kt:441)
       at se.warting.signatureview.views.SignaturePad.current(SignaturePad.kt:217)
       at se.warting.signatureview.views.SignaturePad.addEvent(SignaturePad.kt:185)
       at se.warting.signatureview.views.SignaturePad.onTouchEvent(SignaturePad.kt:250)
       at android.view.View.dispatchTouchEvent(View.java:12716)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3108)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2759)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3108)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2759)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3108)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2759)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3108)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2759)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3108)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2759)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3108)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2759)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3108)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2759)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:543)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1894)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:913)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:489)
       at android.view.View.dispatchPointerEvent(View.java:12960)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6155)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5881)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5339)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5399)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5358)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5525)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5366)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5582)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5339)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5399)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5358)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5366)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5339)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8273)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8242)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8199)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8390)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8357)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8413)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1077)
       at android.view.Choreographer.doCallbacks(Choreographer.java:889)
       at android.view.Choreographer.doFrame(Choreographer.java:815)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1063)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)

**Comment by warting** [comment]
I couldn't reproduce it, but I made it none null-able. Hopefully it wont appear again, and if it does we might get a better source of what the null value comes from.

**Comment by ashik169** [comment]
Thanks for fixing this. But it still happening on v0.1.2

Fatal Exception: java.lang.NullPointerException:
       at se.warting.signatureview.views.SignaturePad.addBezier(SignaturePad.kt:505)
       at se.warting.signatureview.views.SignaturePad.addTimedPoint(SignaturePad.kt:461)
       at se.warting.signatureview.views.SignaturePad.current(SignaturePad.kt:231)
       at se.warting.signatureview.views.SignaturePad.addEvent(SignaturePad.kt:196)
       at se.warting.signatureview.views.SignaturePad.onTouchEvent(SignaturePad.kt:269)
       at android.view.View.dispatchTouchEvent(View.java:11845)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:594)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1978)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:843)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:550)
       at android.view.View.dispatchPointerEvent(View.java:12100)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4966)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4761)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4259)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4329)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4287)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4429)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4295)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4486)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4259)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4329)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4287)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4295)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4259)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6854)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6828)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6783)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6966)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:195)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:182)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6937)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6989)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:980)
       at android.view.Choreographer.doCallbacks(Choreographer.java:792)
       at android.view.Choreographer.doFrame(Choreographer.java:718)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:966)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6711)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
