### ISSUE TITLE
Crash at onDraw() when used with Compose

### ISSUE THREAD

**Issue by jrgonzalezg** [warting/android-signaturepad#218]
**Describe the bug**

We are getting crashes on some devices when using `SignaturePadView` in Compose. There seems to be some Bitmap initialization that is sometimes happening while the view is not yet measured which leads to this crash:
```
Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1118)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1085)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1035)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:996)
       at se.warting.signatureview.views.SignaturePad.ensureSignatureBitmapInOnDraw(SignaturePad.kt:527)
       at se.warting.signatureview.views.SignaturePad.onDraw(SignaturePad.kt:267)
       at android.view.View.draw(View.java:24395)
       at android.view.View.updateDisplayListIfDirty(View.java:23256)
       at android.view.View.draw(View.java:24125)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.draw(View.java:24398)
       at androidx.compose.ui.platform.AndroidViewsHandler.drawView(AndroidViewsHandler.android.kt:72)
       at androidx.compose.ui.platform.AndroidComposeView.drawAndroidView(AndroidComposeView.android.kt:743)
       at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$coreModifier$1.invoke(AndroidViewHolder.android.kt:281)
       at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$coreModifier$1.invoke(AndroidViewHolder.android.kt:278)
       at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:104)
       at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:381)
       at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:371)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
       at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
       at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:397)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:130)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:126)
       at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
       at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotStateKt.java:1)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:396)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
       at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
       at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:298)
       at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:239)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:355)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:64)
       at androidx.compose.foundation.DrawOverscrollModifier.draw(AndroidOverscroll.kt:81)
       at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:381)
       at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:371)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:397)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:130)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:126)
       at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
       at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotStateKt.java:1)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:396)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
       at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
       at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:298)
       at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:239)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:355)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:397)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:130)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:126)
       at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
       at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotStateKt.java:1)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:396)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
       at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
       at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:298)
       at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:239)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:355)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:64)
       at androidx.compose.foundation.Background.draw(Background.kt:107)
       at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:381)
       at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:371)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
       at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
       at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
       at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:360)
       at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:840)
       at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:151)
       at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:368)
       at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:397)
       at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2139)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:130)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:126)
       at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
       at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotStateKt.java:1)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:396)
       at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
       at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
       at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:298)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1010)
       at android.view.View.draw(View.java:24398)
       at android.view.View.updateDisplayListIfDirty(View.java:23256)
       at android.view.View.draw(View.java:24125)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23242)
       at android.view.View.draw(View.java:24125)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23242)
       at android.view.View.draw(View.java:24125)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23242)
       at android.view.View.draw(View.java:24125)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23242)
       at android.view.View.draw(View.java:24125)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23242)
       at android.view.View.draw(View.java:24125)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1531)
       at android.view.View.draw(View.java:24398)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1504)
       at android.view.View.updateDisplayListIfDirty(View.java:23256)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:753)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:759)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:857)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5501)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5194)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4356)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2991)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10665)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
``` 

**To Reproduce**

It is unclear how / when on which devices this happens but it seems to be caused by some recompositions running when the internal signature pad view does not have a size and there is no check to avoid the bitmap creation code in those cases which crashes on creation of bitmaps with no size.

**Expected behavior**

The view should not attempt to create 0 size bitmaps. Could it be possible to safeguard such code so it is not run if the width and height are not greater than 0? When that's the case it will probably be superseded by a later onDraw() pass once the view is properly measured / sized / resized.

**Comment by jrgonzalezg** [comment]
Thanks!, we will soon roll out a new app version including this and let you know if there is still any issue.
